[package]
name = "chess-ai"
version = "0.1.0"
authors = ["dino"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix_display = "0.9"
